// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnFBkOPMwSo7XPIbKR69gvcFrp5uUwLyA',
    appId: '1:171192483195:web:7b6b6add5e7e584c1c51de',
    messagingSenderId: '171192483195',
    projectId: 'smart-cart-be4cd',
    authDomain: 'smart-cart-be4cd.firebaseapp.com',
    storageBucket: 'smart-cart-be4cd.appspot.com',
    measurementId: 'G-88XYB4LF1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1MaaqxtL9Xz3t9as-IsyKq_9edtaAQgc',
    appId: '1:171192483195:android:24e6901d618235631c51de',
    messagingSenderId: '171192483195',
    projectId: 'smart-cart-be4cd',
    storageBucket: 'smart-cart-be4cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2my_6jutQ5akX-24SPFC93jQy4EsK-Wo',
    appId: '1:171192483195:ios:44eaa26d9d54639e1c51de',
    messagingSenderId: '171192483195',
    projectId: 'smart-cart-be4cd',
    storageBucket: 'smart-cart-be4cd.appspot.com',
    iosBundleId: 'com.example.smartCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2my_6jutQ5akX-24SPFC93jQy4EsK-Wo',
    appId: '1:171192483195:ios:b8e66bfc89abf5a81c51de',
    messagingSenderId: '171192483195',
    projectId: 'smart-cart-be4cd',
    storageBucket: 'smart-cart-be4cd.appspot.com',
    iosBundleId: 'com.example.smartCart.RunnerTests',
  );
}
